
server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:9296
  cloud:
    gateway:
      routes:
        - id: MOVIE-SERVICE
          uri: lb://MOVIE-SERVICE
          predicates:
            - Path=/movie/**
          filters:
            - name: CircuitBreaker
              args:
                name: MOVIE-SERVICE
                fallbackUri: forward:/movieServiceFallback
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackUri: forward:/userServiceFallback

# Setup for user authentication with Okta using the Okta Spring Boot Starter.
okta:
  oauth2:
    issuer: https://dev-84928916.okta.com/oauth2/default
    audience: api://default
    client-id: XXXXX
    client-secret: XXXXXX
    scopes: openid, profile, email, offline_access

# Configuration for applications to act as an OAuth2 Resource Server and Client
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://dev-84928916.okta.com/oauth2/default
      client:
        registration:
          internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: openid, profile, email, offline_access
            client-id: XXXXX
            client-secret: XXXXXX
