server:
  port: 8081

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/userdb?allowPublicKeyRetrieval=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "configserver:http://localhost:9296"
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://dev-84928916.okta.com/oauth2/default
      client:
        registration:
          internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oafchkya4QzyPtzS5d7
            client-secret: O9JF2bN7f5ZDZZmsNglvtSyZ4xJod196haHG80judrtCHj-BKpxsF8OHcX6VRO5h

external:
  api:
    base-url: http://localhost:8080/movie

logging:
  level:
    reactor:
      netty:
        http:
          client:
            HttpClient: DEBUG